### ISSUE TITLE
dart-fss-classifier 사용 문의

### ISSUE THREAD

**Issue by paladinz67** [josw123/dart-fss-classifier#1]
안녕하세요, 
계정항목값 불일치 문제 해결을 위해 dart-fss-classifier를 설치하니 오류가 발생합니다.
아래와 같이 dart-fss-classifier 적용 전에는 문제 없이 실행되는데, 

import dart_fss as dart
api_key = '0e3b458c6a7d24ccbcc9056ecb9b5a1e66b5d320'
dart.dart_set_api_key(api_key=api_key)
crp_list = dart.get_crp_list()
samsung = crp_list.find_by_name('삼성전자')[0]
fs = samsung.get_financial_statement(start_dt='20000101')
Annual reports: 100%|██████████| 20/20 [01:05<00:00,  3.26s/report]
fs.save('삼성전자.xlsx')
Out[5]: 'D:\\Proj\\Analytics\\LeeAnalysis\\fsdata\\삼성전자.xlsx'

dart-fss-classifier 적용 시 아래와 같은 에러 메시지가 발생합니다.
dependency package는 모두 설치 했습니다.

import dart_fss_classifier
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
assert dart_fss_classifier.attached_plugin() == True
fs = samsung.get_financial_statement(start_dt='20000101')
Annual reports:  10%|█         | 2/20 [00:06<01:00,  3.34s/report]Traceback (most recent call last):
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss\fs_search.py", line 801, in merge_fs
    ndata, nlabels = compare_func(column, df, ndf, label_df[tp], ndata, nlabels)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss_classifier\fs_search.py", line 109, in compare_df_and_ndf_cnn
    concept_id = guess_concept_id(label)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss_classifier\fs_search.py", line 40, in guess_concept_id
    return guess(text)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss_classifier\classifier.py", line 30, in guess
    c = Classifier()
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss\_utils.py", line 17, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss_classifier\classifier.py", line 132, in __init__
    self.konlpy = Kkma()
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\konlpy\tag\_kkma.py", line 95, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\konlpy\jvm.py", line 55, in init_jvm
    jvmpath = jvmpath or jpype.getDefaultJVMPath()
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\jpype\_core.py", line 337, in getDefaultJVMPath
    return finder.get_jvm_path()
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\jpype\_jvmfinder.py", line 184, in get_jvm_path
    .format(self._libfile))
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-08b25d32b3a6>", line 1, in <module>
    fs = samsung.get_financial_statement(start_dt='20000101')
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss\crp.py", line 176, in get_financial_statement
    report_tp=report_tp, lang=lang, separator=separator)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss\fs_search.py", line 1007, in search_financial_statement
    statements, label_df = merge_fs(statements, label_df, report, fs_tp=fs_tp, separate=separate, lang=lang)
  File "D:\Proj\Analytics\Extracting_from_DART\dart_fss\venv\lib\site-packages\dart_fss\fs_search.py", line 808, in merge_fs
    raise RuntimeError(msg)
RuntimeError: An error occurred while fetching or analyzing {'rcp_no': '20170331004518', 'crp_cls': 'Y', 'crp_nm': '삼성전자', 'crp_cd': '005930', 'rpt_nm': '사업보고서 (2016.12)', 'flr_nm': '삼성전자', 'rcp_dt': '20170331', 'rmk': '연'}.

감사합니다.

**Comment by josw123** [comment]
안녕하세요.

dart-fss-classifier의 의존성 패키지인 KoNLPy 설치시 Python 뿐만아니라 JAVA 설치 및 환경변수 설정이 필요합니다.

오류 해결방법은 [파이썬 한글 형태소 분석기 KoNLPy 설치방법 및 에러 해결](https://ellun.tistory.com/46)을 참고하시면 됩니다.

**Comment by paladinz67** [comment]
감사합니다. ^^

2019년 8월 28일 (수) 오전 11:55, Sungwoo Jo <notifications@github.com>님이 작성:
