### ISSUE TITLE
classifier의 역할에 관한 질문

### ISSUE THREAD

**Issue by HongBeenKim** [josw123/dart-fss-classifier#2]
안녕하세요, 재무제표 데이터 수집에 유용한 툴을 공개해주셔서 감사합니다.

classifier를 사용하면 그렇지 않을 때에 비해서 구체적으로 무엇의 정확도가 얼마나 향상되는지 알 수 있을까요?

document를 읽어보았지만 더 구체적으로 알고싶어서 부연설명을 해주시면 감사하겠습니다.

**Comment by josw123** [comment]
안녕하세요.
Classifier를 사용하는 경우 정확도 향상 시킨다기 보다는 과거 데이터를 좀 더 잘 추출 할 수 있다라고 생각하시면 됩니다.

DART 공시되는 재무제표의 계정항목은 공시연도마다  회사 마다 다른 이름을 사용하는 경우가 빈번하며, 재무제표 처리 기준이 변경되는 경우 데이터값이 변경되는 경우가 많이 있습니다.(예를들어, 2011년 공시에 공시된 2010년 재무제표와 2010년에 공시된 재무제표의 값이 일치 하지 않는 경우가 있습니다.)
DART-FSS 라이브리리의 경우 계정항목명이나 데이터 값을 비교하여 일치하지 않는 경우에는 데이터의 신뢰성을 위해 데이터를 추출하지 않습니다.

Classifier의 경우 자연어 처리를 통해 이러한 항목들의 일부를 추출해 주는 역할을 합니다. 이로인해 과거 일부 데이터를 추가로 추출 할 수 있도록 제작된 것입니다.

국제 회계기준이 도입된 이후의 데이터의 경우(대부분의 기업의 2011년 이후 데이터) Classifier를 사용하지 않으셔도 됩니다. 그러나 그 이전의 데이터를 추출할 경우 classifier를 사용하시면 일부 데이터를 추가로 추출 하실 수 있습니다.

또한 classifier 소스를 참고하셔서 추가 적인 추출 알고리즘을 직접 작성하셔서 사용하시면 데이터 추출 성능이 더 향상 될 것입니다.(classifier는 심플한 자연어 처리만 진행됩니다.)

추가적으로 아래 첨부된 엑셀 파일을 참고하시면 되겠습니다.
(2008년 이전 데이터 위주로 비교하시면 됩니다.)
[005930_annual_with_classifier.xlsx](https://github.com/josw123/dart-fss-classifier/files/3720719/005930_annual_with_classifier.xlsx)
[005930_annual_without_classifier.xlsx](https://github.com/josw123/dart-fss-classifier/files/3720720/005930_annual_without_classifier.xlsx)

**Comment by HongBeenKim** [comment]
자세한 답변 감사드립니다 :)
